TeamsLCFC/config/routes.rb
Rails.application.routes.draw do
  get 'index/index'
  get 'index/mix_teams'
  get 'index/show_teams'
  get 'index/about'

  root 'index#index'

end

TeamsLCFC/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

TeamsLCFC/app/controllers/index_controller.rb
class IndexController < ApplicationController

	helper_method :players_array
	
	#GET
	def index

 	end

	#GET
 	def mix_teams
	end

	#GET
	def show_teams
		if  params[:filter]
			@team_a, @team_b = params[:filter].values.shuffle.each_slice( (params[:filter].values.size/2.0).round ).to_a
		end
		@team_selected = rand(0..1) #peto
	end

	#GET
  	def about

	end

end

TeamsLCFC/app/helpers/application_helper.rb
module ApplicationHelper
end

TeamsLCFC/app/helpers/index_helper.rb
module IndexHelper
end

TeamsLCFC/app/views/index/about.html.erb
<!-- Introduction Row -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">About App
                    <small> - It's Nice to Meet You!</small>
                </h1>
                <p>Here we could mix our teams for Laneros Coworking soccer matches!</p>
            </div>
        </div>

        <!-- Team Members Row -->
        <div class="row">
            <div class="col-lg-12">
                <h2 class="page-header">About Me</h2>
            </div>
            <div class="col-lg-12 text-center">
                <img class="img-circle img-responsive center-block" src="https://avatars2.githubusercontent.com/u/1373345?s=200" alt="Me">
                <h3>Matías Gil
                    <small>iOS - RoR developer</small>
                </h3>
                <p>I like coding, playing videogames and doing some sports ;)</p>
            </div>
        </div>

TeamsLCFC/app/views/index/index.html.erb
<div class="jumbotron">
  <h2>Hello, Laneros Coworking!</h2>

  <h5>Here we can add names of players and then create the teams randomly. Go ahead!</h5>
  <p><a class="btn btn-primary btn-lg" href="<%= index_mix_teams_path %>" role="button">Mix Teams</a></p>
</div>

TeamsLCFC/app/views/index/mix_teams.html.erb
<% if @team_a && @team_a.size > 0 %>
  <script type="text/javascript">
  debugger;
    $('#myModal').modal('show');
  </script>
<% end %>

<div class="row">
	<div class="col-lg-6 col-sm-6 text-center">
	    <h4>1. Add players names</h4>
	</div>
	<div class="col-lg-6 col-sm-6 text-center">
	    <h4>2. Create the teams</h4>
	</div>
</div>
<hr>


<%= form_tag("/index/show_teams", method: "get", class:"form-horizontal") do %>
  <div class="inputs">
    <!-- here we add inputs via JS -->
  </div>
  <div class="form-group col-lg-12">
      <button type="button" class="btn btn-default" aria-label="Left Align" id="add_player">
       <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
      </button>
    </div>
  <div class="row col-lg-12 pull-right">
    <%= submit_tag("Mix Teams", class: "btn btn-default") %>
  </div>
  
<% end %>

TeamsLCFC/app/views/index/show_teams.html.erb
<table class="table table-hover"> 
	<thead> 
		<tr> 
			<th>Team A <% if @team_selected == 1 %><span class="glyphicon glyphicon-asterisk"><% end %></span></th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @team_a.each do |name| %>
		<tr> 
			<td><%= name %></td>
		</tr> 
		<% end %>
	</tbody> 
</table>

<table class="table table-hover"> 
	<thead> 
		<tr> 
			<th>Team B <% if @team_selected == 0 %><span class="glyphicon glyphicon-asterisk"><% end %></th> 
		</tr> 
	</thead> 
	<tbody> 
		<% @team_b.each do |name| %>
		<tr> 
			<td><%= name %></td>
		</tr> 
		<% end %>
	</tbody> 
</table>

TeamsLCFC/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>TeamsLCFC</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <%= javascript_include_tag 'https://js.stripe.com/v2/' %>

    <%= csrf_meta_tags %>

    <!-- Custom CSS -->
    <style>
    body {
        padding-top: 70px;
        /* Required padding for .navbar-fixed-top. Remove if using .navbar-static-top. Change if height of navigation changes. */
    }
    </style>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>
	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="<%= root_path %>">Laneros Coworking FC</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="<%= index_about_path %>">About</a>
                    </li>
                    <li>
                        <a href="<%= index_mix_teams_path %>">Mix Teams</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Page Content -->
    <div class="container">
        <%= yield %>
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; matiasdim 2016</p>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </footer>
    </div>
    <!-- /.container -->

</body>

</html>